### ISSUE TITLE
How to change the represent the Mask

### ISSUE THREAD

**Issue by chumingqian** [Sinha199/Mask-Detection#1]
Hi, SInha199:
      i  was  wandering can i  change the color ,   when  wearing a  mask  i wanna use   Green color  and  NoMask  use the Red color .
   I  tried  to change  the position  of  mask  and  NoMask, but  after that , when i  truly wearing a mask it predict   NoMask with  a red Color.
   Thanks  in advance

**Comment by Sinha199** [comment]
> Hi, SInha199:
> i was wondering can i change the color , when wearing a mask i wanna use Green color and NoMask use the Red color .
> I tried to change the position of mask and NoMask, but after that , when i truly wearing a mask it predict NoMask with a red Color.
> Thanks in advance
Hey ! [darknet bounding box issue](https://github.com/pjreddie/darknet/issues/1045) may this original issue can help you.

**Comment by chumingqian** [comment]
Thanks for your efficient guidance and  quickly reply ,  i change the image.c  in the  "src"file and then remake , it works .
Besides , i am  student in the school  and  join  a  competition, i wanna use your datasets, i would like make a  reference declaration for you  if  you  don't mind.

**Comment by Sinha199** [comment]
> Thanks for your efficient guidance and quickly reply , i change the image.c in the "src"file and then remake , it works .
> Besides , i am student in the school and join a competition, i wanna use your datasets, i would like make a reference declaration for you if you don't mind.

Yeah Sure:)you can
